# ***Case NPS Preditivo***

### **Objetivo**
##### Analise de base preditiva, com foco na validação, definição, identificão e resolução do NPS da base.

 ### **Analise 1**

 #### Quais fatores operacionais influenciam a satisfação do cliente em um e-commerce e como a empresa pode agir de forma proativa para melhorar a experiência antes mesmo da aplicação do NPS, considerando qual problema de negócio está sendo resolvido, a importância do NPS para o setor, as áreas que podem se beneficiar desses insights (como logística, atendimento, pricing e produto), seus impactos em recompra, boca a boca e participação de mercado, além da definição da variável que representa a satisfação do cliente, os motivos de sua escolha, o momento da jornada em que é coletada e os possíveis riscos de seu uso inadequado?

### **Resolução 1**

#### O NPS impacta diretamente o desempenho do e-commerce, pois quanto maior a satisfação do cliente, maior é a tendência de recompra, enquanto clientes detratores podem prejudicar a reputação da marca por meio de avaliações negativas, ao contrário dos promotores, que contribuem com indicações e fortalecem o "boca a boca" positivo, além disso, uma experiência ruim aumenta significativamente as chances de perda de clientes para a concorrência.

### **Analise 2**

#### Quais fatores operacionais realmente influenciam a satisfação do cliente e como a empresa pode agir de forma proativa para melhorar a experiência antes mesmo da aplicação da pesquisa de NPS?

#### Qual problema de negócio está sendo resolvido, por que o NPS é importante para um e-commerce e quais áreas da empresa podem se beneficiar desses insights?

### **Resolução 2**

####  Fator: Agilidade de serviço(Logistica , atendimento , Suporte), qualidade. Sugestão: Resposta de mensagem ao cliente(suporte),  formulario de Leads para captacao de sugestões, ofertas promocionais para possiveis incomodos pelo atraso ou algum empecilho na entrega atual.

#### O problema de negócio está relacionado à necessidade de oferecer um atendimento de qualidade que contribua para o aumento de clientes, construção de uma boa reputação e incentivo à recompra por meio do NPS. Esse indicador é importante para o e-commerce porque mede o nível de satisfação do cliente e sua propensão a recomendar a empresa após a compra, e seus insights podem beneficiar todos os setores, já que o cliente geralmente aponta a criticidade da sua experiência, permitindo identificar melhorias em diferentes áreas da operação.

### **Analise 3**

#### Qual variável representa a satisfação do cliente, por que ela foi escolhida, em que momento da jornada essa informação é coletada e quais são os riscos de utilizá-la de forma inadequada?

### **Resolução 3**

#### A variável que representa a satisfação do cliente é o NPS Score, pois ele reflete a nota média atribuída pelo cliente em relação à sua experiência. Essa informação é coletada após a realização da compra, permitindo avaliar a percepção completa da jornada, e seu uso inadequado pode gerar distorções, especialmente se for aplicado antes da finalização da compra, comprometendo a confiabilidade dos resultados.

## **Importação e Scripts**

##### Importação das bibliotecas para utilização na analise. Juntamente com a importação da base de dados e visualização do head da mesma.

In [2]:
import pandas as pd # Manipulação e analise dos dados
import numpy as np # Manipulação de operações matematicas.
import matplotlib.pyplot as plt # Criação de graficos.
import seaborn as sns # Manipulação e visualização de estatisticas mais avançadas e estilizadas.


df = pd.read_csv('desafio_nps_fase.csv') # Importação da base de dados
df.head() # Leitura do cabeçalho

,customer_id,customer_age,customer_region,customer_tenure_months,order_id,order_value,items_quantity,discount_value,payment_installments,delivery_time_days,delivery_delay_days,freight_value,delivery_attempts,customer_service_contacts,resolution_time_days,nps_score,repeat_purchase_30d,complaints_count,csat_internal_score
0,1,63,Nordeste,14,50001,139.73,4,39.35,4,2,2,55.53,3,0,4,6.9,0,3,6.5
1,2,20,Sul,1,50002,458.95,2,9.51,10,6,4,28.23,3,0,10,2.4,0,3,0.0
2,3,46,Nordeste,111,50003,507.06,5,42.82,6,6,1,40.99,1,4,5,4.8,0,7,1.5
3,4,52,Centro-Oeste,117,50004,302.19,2,19.58,9,5,2,35.24,3,1,11,5.9,0,4,0.3
4,5,56,Norte,50,50005,253.06,1,29.37,11,13,1,39.32,1,1,0,6.1,0,3,7.9

##### Explorando mais os dados para conseguir entender mais sobre a base de dados, com a quantidade de dados e os tipos das variaveis presentes.

In [3]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer_id                2500 non-null   int64
 1   customer_age               2500 non-null   int64
 2   customer_region            2500 non-null   object
 3   customer_tenure_months     2500 non-null   int64
 4   order_id                   2500 non-null   int64
 5   order_value                2500 non-null   float64
 6   items_quantity             2500 non-null   int64
 7   discount_value             2500 non-null   float64
 8   payment_installments       2500 non-null   int64
 9   delivery_time_days         2500 non-null   int64
 10  delivery_delay_days        2500 non-null   int64
 11  freight_value              2500 non-null   float64
 12  delivery_attempts          2500 non-null   int64
 13  customer_service_contacts  2500 non-null   int64
 14  resolution_time_days       2500 non-null   int64
 15  nps_score                  2500 non-null   float64
 16  repeat_purchase_30d        2500 non-null   int64
 17  complaints_count           2500 non-null   int64
 18  csat_internal_score        2500 non-null   float64
dtypes: float64(5), int64(13), object(1)
memory usage: 371.2+ KB

,customer_id,customer_age,customer_tenure_months,order_id,order_value,items_quantity,discount_value,payment_installments,delivery_time_days,delivery_delay_days,freight_value,delivery_attempts,customer_service_contacts,resolution_time_days,nps_score,repeat_purchase_30d,complaints_count,csat_internal_score
count,2500.00000,2500.000000,2500.000000,2500.00000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000
mean,1250.50000,43.396000,61.322400,51250.50000,434.259740,3.470800,29.745620,6.004000,8.022000,2.187200,38.217016,2.005600,1.519600,5.485600,4.378600,0.087200,4.150400,2.941600
std,721.83216,14.888487,34.478729,721.83216,289.772497,1.687331,29.225603,3.159743,3.770411,1.454442,12.076074,0.815497,1.231512,3.458002,2.510229,0.282184,1.784223,2.378957
min,1.00000,18.000000,1.000000,50001.00000,7.760000,1.000000,0.020000,1.000000,2.000000,0.000000,2.620000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,625.75000,31.000000,31.000000,50625.75000,220.245000,2.000000,8.885000,3.000000,5.000000,1.000000,29.927500,1.000000,1.000000,2.000000,2.600000,0.000000,3.000000,0.700000
50%,1250.50000,43.000000,62.000000,51250.50000,375.515000,3.000000,20.935000,6.000000,8.000000,2.000000,38.500000,2.000000,1.000000,6.000000,4.400000,0.000000,4.000000,2.800000
75%,1875.25000,56.000000,91.000000,51875.25000,577.290000,5.000000,40.832500,9.000000,11.000000,3.000000,46.270000,3.000000,2.000000,8.000000,6.100000,0.000000,5.000000,4.800000
max,2500.00000,69.000000,119.000000,52500.00000,1983.810000,6.000000,230.330000,11.000000,14.000000,8.000000,76.130000,3.000000,7.000000,11.000000,10.000000,1.000000,11.000000,10.000000

##### Divisão da nota do NPS em grupos (Detrator, Neutro e Promotor) para conseguir ver a satisfação dos clientes.

In [4]:
# Divisão de grupos e definição de score para que consigamos classifica-los e analisa-los de forma mais precisa
def classificar_nps(score):
    if score <= 6:
        return 'Detrator'
    elif score <= 8:
        return 'Neutro'
    else:
        return 'Promotor'

df['nps_group'] = df['nps_score'].apply(classificar_nps)

In [5]:
df['nps_group'].value_counts(normalize=True)

nps_group
Detrator    0.7404
Neutro      0.1792
Promotor    0.0804
Name: proportion, dtype: float64

##### De acordo com esses dados é possivel analisar que em sua maioria os clientes são detratores, assim percebemos que há problemas com a experiência do cliente.

##### Analisando e comparando por grupo, para entender os padrões que podem estar ocorrendo para que os clientes virem detratores

In [6]:
df.groupby('nps_group')[[
    'delivery_delay_days',
    'complaints_count',
    'customer_service_contacts',
    'resolution_time_days'
]].mean()

,delivery_delay_days,complaints_count,customer_service_contacts,resolution_time_days
nps_group,,,,
Detrator,2.534306,4.622907,1.694219,5.793625
Neutro,1.395089,2.986607,1.129464,4.832589
Promotor,0.756219,2.393035,0.781095,4.104478

##### Podemos identificar que de acordo com a analise desses dados, os detratores tem um comportamento padrão com relação ao atraso na entrega, reclamações e com isso um aumento ao contatar o suporte. Logo gerando uma insatisfação no serviço prestado.

##### Analisando para ver se achamos o ponto de ruptura do NPS

In [7]:
df.groupby('complaints_count')['nps_score'].mean()

complaints_count
0     8.517391
1     7.770492
2     6.052347
3     4.910059
4     4.219167
5     3.645270
6     3.062030
7     2.813609
8     2.065079
9     2.487500
10    2.281818
11    0.850000
Name: nps_score, dtype: float64

##### Com base no ponto de ruptura, podemos identificar que a partir do 2 dia de atraso, o NPS cai drasticamente.